# Generated by Django 4.2 on 2025-05-13 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(help_text='RTSP URL or device index', max_length=200)),
                ('camera_type', models.CharField(choices=[('USB', 'Local USB Cam'), ('RTSP', 'RTSP/IP Cam')], max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Footage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('clip', models.FileField(upload_to='footage/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.camera')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Object', 'Object Detection'), ('Abnormal', 'Abnormal Activity'), ('Face', 'Face Recognition')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Critical', 'Critical')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='snapshots/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.camera')),
            ],
        ),
    ]
