# Generated by Django 4.2 on 2025-05-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_attendance_remove_event_camera_remove_footage_camera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip_file', models.FileField(upload_to='anomaly_clips/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
