# Generated by Django 4.2 on 2025-05-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_anomalyclip'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalyclip',
            name='severity',
            field=models.CharField(default='Unusual', max_length=10),
        ),
    ]
